// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dbHGYj6bAT5a9puw4ZPFAE
// Component: jijq7KHuw464
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection2 from "../../HeroSection2"; // plasmic-import: N7m7eE-uE1FT/component
import Button from "../../Button"; // plasmic-import: tW89Zefd9lZn/component
import Divider from "../../Divider"; // plasmic-import: 4nJSUNUrt-9u/component
import Textinput from "../../Textinput"; // plasmic-import: eIEF-Rw_dvNw/component
import Navigation from "../../Navigation"; // plasmic-import: ZnkrLNpX776i/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: eSl55x41OoSE/component
import Valueprop from "../../Valueprop"; // plasmic-import: iqLVo_SBs1q1/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: -ldHHZatxycY/component
import ListItem from "../../ListItem"; // plasmic-import: ygq9q7fdnsDN/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: EEEJ5WMuY1cN/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: -58tpuVqM8kJ/component
import Banner from "../../Banner"; // plasmic-import: uXEfCpaPOcQp/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: XsCpixfwfjX3/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: eIZGvIxMUFp7/component
import Testimonial from "../../Testimonial"; // plasmic-import: 0IQ_Zu-6dz81/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: PzVBxOVt1zUE/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: DMr5Kga86Q9B/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: dbHGYj6bAT5a9puw4ZPFAE/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: jijq7KHuw464/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: qMBAqKPwaUKX/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: H9zzvpyBx8HG/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: En7D2-mrgnlW/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: wbpeHCM_Sln2/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: xgFvDdTt8WnB/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: iH81psM_-rIs/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: DTVaLWyfxhm9/icon
import image13DpqiL1Yu4Ow from "./images/image13.svg"; // plasmic-import: dpqi-L1Yu4OW/picture
import loomsvg2WUf6PyhAlIot from "./images/loomsvg2.svg"; // plasmic-import: wUf6PYHAlIOT/picture
import strapisvg26PI9PAxCHoWq from "./images/strapisvg2.svg"; // plasmic-import: 6pI9PAxCHoWQ/picture
import segmentsvg2NSbGHaHtUnI from "./images/segmentsvg2.svg"; // plasmic-import: nSB-GHaHtUnI/picture
import xstate1SvgVkgqRnQVuYnX from "./images/xstate1Svg.svg"; // plasmic-import: vkgqRnQVuYnX/picture
import mapboxsvg233Vvi961IF from "./images/mapboxsvg2.svg"; // plasmic-import: -33VVI961i_f/picture

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  heroSection2?: p.Flex<typeof HeroSection2>;
  navigation?: p.Flex<typeof Navigation>;
  valuesSection3?: p.Flex<typeof ValuesSection3>;
  h2?: p.Flex<"h2">;
  valuesSection2Dark?: p.Flex<typeof ValuesSection2Dark>;
  pricingSection3?: p.Flex<typeof PricingSection3>;
  shopBanners?: p.Flex<typeof ShopBanners>;
  logoCloudSection2?: p.Flex<typeof LogoCloudSection2>;
  testimonialsSection1?: p.Flex<typeof TestimonialsSection1>;
  callToActionSection1?: p.Flex<typeof CallToActionSection1>;
};

export interface DefaultHomepageProps {
  className?: string;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__o50Zr)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__oFwNy)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__kc7A)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___5MGdb
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gsZrl
                      )}
                    >
                      <span>
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span style={{ textDecoration: "underline" }}>
                          {"adapt"}
                        </span>
                      </span>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__olTzm
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__kfuf5)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__dJuey
                      )}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__nqDRl
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      }
                    />

                    <Button
                      bgDifference={"bgDifference" as const}
                      className={classNames(
                        "__wab_instance",
                        sty.button__miMye
                      )}
                      darkGray={"darkGray" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__h5Um
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__gXzX6)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox___1Y6Xn)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___6WO4Z
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__icje2
                        )}
                      >
                        {"Sign up with"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__vmzEx
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__fXxYz
                          )}
                          ouline={"ouline" as const}
                          slot={"Apple"}
                          startIcon={"startIcon" as const}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__qTjBv
                          )}
                          ouline={"ouline" as const}
                          slot={"Google"}
                          startIcon={"startIcon" as const}
                        >
                          <Icon6Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__klXn6
                            )}
                            role={"img"}
                          />
                        </Button>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__pwl7
                        )}
                      >
                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__xlcUf
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__eMcT4
                          )}
                        >
                          {"Or"}
                        </div>

                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__rShi
                          )}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__qsp4L
                        )}
                      >
                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__d0APn
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__iVynA
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__eIe87
                          )}
                        />
                      </p.Stack>

                      <Button
                        children2={
                          <Icon5Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__wu9Zy
                            )}
                            role={"img"}
                          />
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button___6N3Kh
                        )}
                        colors={"indigo" as const}
                        slot={"Start your account"}
                      />
                    </p.Stack>

                    <Divider
                      className={classNames(
                        "__wab_instance",
                        sty.divider__rhZlq
                      )}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__qCtfc)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__k7M2D
                        )}
                      >
                        {
                          "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
                        }
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          >
            <Navigation
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames("__wab_instance", sty.navigation)}
              hideCta={"hideCta" as const}
              slot={
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button___95KSl)}
                    link={"#services" as const}
                    navLink={"navLink" as const}
                    slot={"Services"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___2FUqK)}
                    link={"#features" as const}
                    navLink={"navLink" as const}
                    slot={"Features"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___72TW3)}
                    link={"#pricing" as const}
                    navLink={"navLink" as const}
                    slot={"Pricing"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__nHkO)}
                    link={"#testimonials" as const}
                    navLink={"navLink" as const}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__idMc4
                        )}
                      >
                        {"Testimonials"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__eAaPd)}
                    navLink={"navLink" as const}
                    slot={"Log in"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__c1IwN)}
                    darkGray={"darkGray" as const}
                    slot={"Sign up"}
                  />
                </React.Fragment>
              }
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__maxG)}
                role={"img"}
                src={image13DpqiL1Yu4Ow}
              />
            </Navigation>
          </HeroSection2>

          <div
            className={classNames(defaultcss.all, sty.freeBox__ed6Nq)}
            id={"services" as const}
          >
            <ValuesSection3
              data-plasmic-name={"valuesSection3"}
              data-plasmic-override={overrides.valuesSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__wjyhV)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__saNFu)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          defaultcss.h2,
                          defaultcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Proposing values"}
                      </h2>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__r17P
                      )}
                    >
                      {
                        "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__uIaXq)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__th4Fz)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___9Dysi
                        )}
                        flat={"flat" as const}
                        slot={
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___9GI4P
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Powerful"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__c6To1
                        )}
                        flat={"flat" as const}
                        slot={
                          "Consequat scelerisque a eros taciti nisl a sodales."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pIbrG
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Faster"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___0PDdd
                        )}
                        flat={"flat" as const}
                        slot={"At ut condimentum amet adipiscing ac diam a."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__onBCm
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Best and brightest"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__tNfBo
                        )}
                        flat={"flat" as const}
                        slot={
                          "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___3PVyB
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__jQizu
                          )}
                        >
                          {"Dynamic range"}
                        </div>
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___8OMiH)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__rd4Ge)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__dCbEm
                        )}
                        flat={"flat" as const}
                        slot={
                          "Commodo pretium himenaeos nisi potenti ad in ante."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__eOHtg
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__cy8IU
                          )}
                        >
                          {"Portable"}
                        </div>
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__rWeOk
                        )}
                        flat={"flat" as const}
                        slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__rsCn
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Production-ready"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__xwlfh
                        )}
                        flat={"flat" as const}
                        slot={
                          "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__g5Sct
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Magical"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__cKlxa
                        )}
                        flat={"flat" as const}
                        slot={
                          "A parturient mi suspendisse nisl inceptos nullam a."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__cdWqr
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Accessible"}
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox___9HokF)}
            id={"features" as const}
          >
            <ValuesSection2Dark
              data-plasmic-name={"valuesSection2Dark"}
              data-plasmic-override={overrides.valuesSection2Dark}
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox___55YJ)}
            id={"pricing" as const}
          >
            <PricingSection3
              data-plasmic-name={"pricingSection3"}
              data-plasmic-override={overrides.pricingSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__c5JSp)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__rtVvI)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__eNhZa
                        )}
                      >
                        {"Pricing plans"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__gIRgA
                      )}
                    >
                      {
                        "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___6Olwb)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___4Ix6W
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___9KAen
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__oqi59
                          )}
                        >
                          {"Starter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__bSnEb
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__cLihd
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox___1Lrlh
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__bX9QO
                              )}
                            >
                              {"8"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__kmkd9
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider___9GBkg
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__wuJqw
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox___8GxD3
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__aaVpQ
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__uOlcw
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__naCsn
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__sTez
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Mus consequat a justo"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__qRiNq
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__mZjXy
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__fcYwu
                              )}
                            >
                              {"Buy starter"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__dC39L)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__ixzrC
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__hnNuO
                          )}
                        >
                          {"Pro"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__kkfnQ
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__pP5G8
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__i3S4
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__mslx1
                              )}
                            >
                              {"16"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__cPPnY
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__yBbjf
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___9LPdZ
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__yxaYf
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__uaRjY
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Ligula primis mollis sem dignissim semper lectus parturient"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__whWbB
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__marZ4
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__qx52O
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__cMmuh
                                )}
                              >
                                {
                                  "A curabitur dignissim pharetra porta suscipit"
                                }
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__kfGtQ
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__hpKp8
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___7Jd2H
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "Condimentum diam a et sapien praesent potenti torquent a eros"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___6IIgv
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__oyuQ
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___3LNmV
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__zja3C
                                )}
                              >
                                {"Conubia in hac eu elementum sodales"}
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__uSSjQ
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___0MPe9
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"green" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__sgaFt
                              )}
                            >
                              {"Buy pro"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__k3YLk)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__wbZKc
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___4LpPn
                          )}
                        >
                          {"Team"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__p8Vi
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__ppq8R
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__liAi
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__wgCpS
                              )}
                            >
                              {"10"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__hTheo
                            )}
                          >
                            {"/member"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider___8QXei
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__hiGxb
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__uNdz2
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__lwldm
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={"Ad nam curae a potenti platea"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__wf6Cq
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__aO9th
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__e8A75
                            )}
                            flatIcon={"flatIcon" as const}
                            justDescription={"justDescription" as const}
                            slot={
                              "A adipiscing scelerisque pretium consectetur sem"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__uGdgX
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__q5R58
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white" as const}
                          extraSmallShadow={"extraSmallShadow" as const}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__xS4Hg
                              )}
                            >
                              {"Buy team"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          >
            <Banner
              className={classNames("__wab_instance", sty.banner___9TeuC)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__xysiI
                    )}
                  >
                    {"Sunglasses Collection"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___4Le3J
                    )}
                  >
                    {"Get 25% off on selected items"}
                  </div>

                  <Button
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___3AI2B
                        )}
                      >
                        {"Go to collection ->"}
                      </div>
                    }
                  />
                </React.Fragment>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__gekti)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__vZ1Jr)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__rQvI7
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kjXy
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__h45Iy
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__sVmJr)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80" as const
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner__c6QHz)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__pkFQt
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__yx1F5
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__kokOn
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__maJsn)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80" as const
                  }
                />
              </Banner>
            </p.Stack>
          </ShopBanners>

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <div
            className={classNames(defaultcss.all, sty.freeBox__tNysT)}
            id={"testimonials" as const}
          >
            <TestimonialsSection1
              data-plasmic-name={"testimonialsSection1"}
              data-plasmic-override={overrides.testimonialsSection1}
            >
              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__x1Zth)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__vUaTp)}
                    role={"img"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj" as const
                    }
                  />
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__seGaK)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__eu0Rz)}
                    role={"img"}
                    src={
                      "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png" as const
                    }
                  />
                }
                slot2={"Elaine Benes"}
                slot3={"Editor, Pendant Publishing"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__p8Dp5
                  )}
                >
                  {'"Vestibulum lacinia varius habitant dis aenean.'}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__d9Fvb
                  )}
                >
                  {
                    'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__kCbqd)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__iHwyv)}
                    role={"img"}
                    src={
                      "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg" as const
                    }
                  />
                }
                slot2={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__bRp2
                    )}
                  >
                    {"Woody Boyd"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__aaVlv
                    )}
                  >
                    {"Assistant Bartender, Cheers"}
                  </div>
                }
              >
                {
                  '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
                }
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__ttMv6)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__kKglo)}
                    role={"img"}
                    src={
                      "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg" as const
                    }
                  />
                }
                slot2={"Louis Huang"}
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__mgDz
                    )}
                  >
                    {"Restaurant Owner, Cattleman's Ranch"}
                  </div>
                }
              >
                {
                  '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                }
              </Testimonial>
            </TestimonialsSection1>
          </div>

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection2",
    "navigation",
    "valuesSection3",
    "h2",
    "valuesSection2Dark",
    "pricingSection3",
    "shopBanners",
    "logoCloudSection2",
    "testimonialsSection1",
    "callToActionSection1"
  ],
  heroSection2: ["heroSection2", "navigation"],
  navigation: ["navigation"],
  valuesSection3: ["valuesSection3", "h2"],
  h2: ["h2"],
  valuesSection2Dark: ["valuesSection2Dark"],
  pricingSection3: ["pricingSection3"],
  shopBanners: ["shopBanners"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  callToActionSection1: ["callToActionSection1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  heroSection2: typeof HeroSection2;
  navigation: typeof Navigation;
  valuesSection3: typeof ValuesSection3;
  h2: "h2";
  valuesSection2Dark: typeof ValuesSection2Dark;
  pricingSection3: typeof PricingSection3;
  shopBanners: typeof ShopBanners;
  logoCloudSection2: typeof LogoCloudSection2;
  testimonialsSection1: typeof TestimonialsSection1;
  callToActionSection1: typeof CallToActionSection1;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection2: makeNodeComponent("heroSection2"),
    navigation: makeNodeComponent("navigation"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    h2: makeNodeComponent("h2"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    shopBanners: makeNodeComponent("shopBanners"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
